# Generated by Django 3.2.6 on 2024-10-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
