# Generated by Django 3.2.6 on 2024-10-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_credential_issuer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='credential_type',
            field=models.IntegerField(default=None),
        ),
    ]
