# Generated by Django 3.2.6 on 2024-10-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_credential_credential_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='issuer_address',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
