# Generated by Django 3.2.6 on 2024-10-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_credential_issuer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
