# Generated by Django 3.2.6 on 2024-11-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_notification_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('student_last_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('horary_zone', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
